# Generated by Django 3.2.9 on 2021-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_sellos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='totalAzucares',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='totalCalorias',
            field=models.FloatField(default=0),
        ),
    ]
