# Generated by Django 3.2.9 on 2021-12-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_sellos', '0002_auto_20211220_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='totalCalorias',
            field=models.FloatField(),
        ),
    ]
