# Generated by Django 3.2.9 on 2021-12-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_sellos', '0003_alter_ingrediente_totalcalorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='totalAzucares',
        ),
    ]
