# Generated by Django 3.2.9 on 2021-12-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_sellos', '0006_ingrediente_totalsodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='totalGrasas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
