# Generated by Django 3.2.9 on 2021-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_sellos', '0007_ingrediente_totalgrasas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_grupo_usuario',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Pyme', 'Pyme')], max_length=20),
        ),
    ]
