# Generated by Django 3.2.9 on 2021-12-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0007_rename_user_name_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='user_name',
        ),
    ]
