# Generated by Django 3.2.9 on 2021-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0008_rename_username_usuario_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.CharField(max_length=300),
        ),
    ]
