# Generated by Django 3.2.9 on 2021-12-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0009_alter_usuario_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('owner', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='calculadora_nutricional.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('language', models.CharField(max_length=3)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='calculadora_nutricional.collection')),
            ],
        ),
    ]
