# Generated by Django 3.2.9 on 2021-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0011_auto_20211208_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comentario', models.CharField(max_length=50)),
                ('apellido_comentario', models.CharField(max_length=50)),
                ('comentario', models.TextField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
