# Generated by Django 3.2.9 on 2021-12-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0012_auto_20211208_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
