# Generated by Django 3.2.9 on 2021-12-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0013_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='apellido_comentario',
        ),
    ]
