# Generated by Django 3.2.9 on 2021-12-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0014_remove_comentario_apellido_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_comentario',
        ),
    ]
