# Generated by Django 3.2.9 on 2021-12-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0016_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
