# Generated by Django 3.2.9 on 2021-12-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0018_product_productmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeta',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductMeta',
        ),
    ]
