# Generated by Django 3.2.9 on 2021-12-09 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0019_auto_20211209_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('porcion_habitual', models.FloatField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=50)),
                ('cantidad_ingrediente', models.FloatField()),
                ('calorias', models.FloatField()),
                ('azucares', models.FloatField()),
                ('grasas', models.FloatField()),
                ('sodio', models.FloatField()),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora_nutricional.receta')),
            ],
        ),
    ]
