# Generated by Django 3.2.9 on 2021-12-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_nutricional', '0020_ingrediente_receta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
